Repository qutebrowser/qutebrowser, pull requests merged in 2018-08, with the labels that each got.

#4103 Add No-Script-like JavaScript blocking to FAQ
  doc/faq.asciidoc
Labels: status: needs review

#4120 Fix #4114 importer.py may fail on chrome bookmarks import
  scripts/importer.py
Labels: bug: behavior, priority: 1 - middle, status: needs review, status: work in progress

#4123 Add slackware installation instructions
  doc/install.asciidoc
Labels: status: needs review

#4105 Show warning when using --backend with a running instance
  qutebrowser/app.py
Labels: status: needs review

#4126 Have :repeat be able to use [count]
  doc/help/commands.asciidoc
  qutebrowser/misc/utilcmds.py
  tests/end2end/features/utilcmds.feature
Labels: status: needs review

#4118 Tests for ipv6 support in urlmatch
  qutebrowser/config/configdata.py
  qutebrowser/utils/urlmatch.py
  tests/unit/utils/test_urlmatch.py
Labels: status: needs review

#4138 Fix double-escaping on qute://log
  doc/changelog.asciidoc
  qutebrowser/utils/log.py
Labels: priority: 2 - low, status: needs review

#4153 Set desktop file name
  qutebrowser/app.py
Labels: status: needs review

#4156 Add instructions to link against OpenSSL 1.0 on Ubuntu
  doc/install.asciidoc
Labels: status: needs review

#4140 Sort tab completion properly with more than 9 tabs.
  qutebrowser/completion/models/miscmodels.py
  tests/unit/completion/test_models.py
Labels: status: needs review

#4148 Add two similar projects to the Active list in README.
  README.asciidoc
Labels: component: docs, easy, priority: 2 - low, status: needs review
