Repository qutebrowser/qutebrowser, pull requests merged in 2018-04, with the labels that each got.

#3820 Added surrounding gray box to launch command for Ubuntu + Tox
  doc/install.asciidoc
Labels: component: docs, status: needs review

#3792 Greasemonkey: fix early GM_addStyle with fast sites.
  qutebrowser/javascript/greasemonkey_wrapper.js
Labels: status: needs review, status: stale

#3802 Fix win_id 0 always being included in :tab-take completion
  qutebrowser/completion/models/miscmodels.py
  tests/unit/completion/test_models.py
Labels: bug: behavior, component: completion, priority: 2 - low, status: needs review

#3807 Add option to mute the Last Tab/First Tab messages when tabs.wrap is false
  qutebrowser/browser/commands.py
  tests/end2end/features/tabs.feature
Labels: status: needs review

#3803 Greasemonkey: fix default include value
  qutebrowser/browser/greasemonkey.py
Labels: status: needs review

#3813 Stop read timer when download is cancelled
  qutebrowser/browser/qtnetworkdownloads.py
Labels: status: needs review, status: stale

#3791 Add userscript to download bibtex for DOI scraped from current tab
  misc/userscripts/getbib
Labels: status: needs review, status: stale
