Repository qutebrowser/qutebrowser, pull requests merged in 2018-06, with the labels that each got.

#3963 Add note about base16-qutebrowser
  doc/help/configuring.asciidoc
Labels: status: needs review, status: stale

#3944 Prevent closing :report dialog when pressing <escape>
  qutebrowser/config/configdata.yml
  qutebrowser/misc/crashdialog.py
Labels: status: needs review, status: stale

#3930 Clarify install command for Ubuntu 17.04
  doc/install.asciidoc
Labels: component: docs, status: needs review, status: stale

#3929 LastPass password fill implementation based off qute-pass code
  misc/userscripts/qute-lastpass
Labels: easy, priority: 3 - wishlist, status: needs review, status: stale

#3926 appdata: install the metainfo using the Makefile
  misc/Makefile
  misc/qutebrowser.appdata.xml
Labels: status: needs review

#3654 Add --pygment argument to view-source
  qutebrowser/browser/browsertab.py
  qutebrowser/browser/commands.py
  qutebrowser/browser/webengine/webenginetab.py
  qutebrowser/browser/webkit/webkittab.py
Labels: status: stale

#3940 Change caret style
  qutebrowser/javascript/caret.js
Labels: component: QtWebEngine, component: ui, language: javascript, priority: 2 - low, status: needs review

#3991 build_release.py: Get python path from registry on Windows
  scripts/dev/build_release.py
Labels: status: needs review
