Repository qutebrowser/qutebrowser, pull requests merged in 2018-03, with the labels that each got.

#3652 Resolve empty completion.timestamp_format crash.
  qutebrowser/completion/models/histcategory.py
  tests/unit/completion/test_histcategory.py
Labels: bug: exception, component: completion, component: config, priority: 1 - middle, status: needs review

#3659 Clear old search results on webkit
  qutebrowser/browser/webkit/webkittab.py
Labels: status: needs review

#3660 Don't crash first completion update with min_chars.
  qutebrowser/completion/completer.py
  tests/unit/completion/test_completer.py
Labels: bug: exception, component: completion, priority: 2 - low, status: needs review

#3666 Greasemonkey: don't inject JS into dead frames
  qutebrowser/browser/webkit/webpage.py
Labels: bug: exception, priority: 1 - middle, status: needs review

#3689 keyinput: Merge keyparser into modeparsers
  qutebrowser/keyinput/keyparser.py
  qutebrowser/keyinput/modeman.py
  qutebrowser/keyinput/modeparsers.py
Labels: status: needs review

#3700 Show version for POSIX OSes
  qutebrowser/utils/version.py
  tests/conftest.py
  tests/unit/utils/test_version.py
Labels: status: needs review

#3695 Update flake8-per-file-ignores to version 0.5
  .flake8
  misc/requirements/requirements-flake8.txt
Labels: status: needs review

#3606 add basic completion to file dialog
  qutebrowser/mainwindow/prompt.py
  tests/unit/mainwindow/test_prompt.py
Labels: status: needs review

#3613 Refactor TabbedBrowser from inheritance to composition
  qutebrowser/app.py
  qutebrowser/browser/commands.py
  qutebrowser/browser/hints.py
  qutebrowser/browser/signalfilter.py
  qutebrowser/completion/models/miscmodels.py
  qutebrowser/mainwindow/mainwindow.py
  qutebrowser/mainwindow/statusbar/backforward.py
  qutebrowser/mainwindow/statusbar/bar.py
  qutebrowser/mainwindow/tabbedbrowser.py
  qutebrowser/mainwindow/tabwidget.py
  qutebrowser/misc/sessions.py
  qutebrowser/misc/utilcmds.py
  qutebrowser/utils/objreg.py
  tests/helpers/stubs.py
  tests/unit/browser/test_signalfilter.py
  tests/unit/completion/test_models.py
  tests/unit/mainwindow/statusbar/test_backforward.py
  tests/unit/mainwindow/test_tabwidget.py
Labels: status: stale

#3715 Greasemonkey: add FAQ entry.
  doc/faq.asciidoc
Labels: component: docs, status: needs review

#3733 Add correct maximum and minimum value for tabs.switching_delay
  qutebrowser/config/configdata.yml
Labels: bug: exception, component: config, easy, priority: 1 - middle, status: needs review

#3728 Fix: restrict output of `task` to one line (closes #3726)
  misc/userscripts/taskadd
Labels: bug: behavior, priority: 2 - low, status: needs review

#3749 Add 32bit color for Windows icon
  icons/qutebrowser.ico
Labels: status: needs review

#3767 Pyinstaller: don't use upx
  misc/qutebrowser.spec
Labels: status: needs review

#3751 Always display plain titles in tab tooltips
  qutebrowser/mainwindow/tabwidget.py
Labels: component: ui, priority: 3 - wishlist

#3680 Add option to only show favicons for pinned tabs
  qutebrowser/browser/browsertab.py
  qutebrowser/browser/commands.py
  qutebrowser/config/configdata.yml
  qutebrowser/config/configfiles.py
  qutebrowser/mainwindow/tabbedbrowser.py
  qutebrowser/mainwindow/tabwidget.py
  tests/helpers/stubs.py
  tests/unit/config/test_configfiles.py
Labels: component: ui, easy, priority: 2 - low, status: needs review

#3788 Escape strings with string_escape rather than tojson
  qutebrowser/browser/greasemonkey.py
  qutebrowser/javascript/greasemonkey_wrapper.js
Labels: bug: exception, status: needs review
