Repository qutebrowser/qutebrowser, pull requests merged in 2018-09, with the labels that each got.

#4178 Display value when calling :set without a value
  doc/help/commands.asciidoc
  qutebrowser/config/configcommands.py
  tests/unit/config/test_configcommands.py
Labels: status: needs review

#4107 ./misc/Makefile: Use of variables
  misc/Makefile
Labels: easy, priority: 2 - low, status: needs review

#4207 add proper multiline support for qute-pass
  misc/userscripts/qute-pass
Labels: status: needs review

#4029 userscripts: README page and qurlshare userscript
  misc/userscripts/README.md
Labels: status: needs review

#4231 Add bindings to toggle content.images
  qutebrowser/config/configdata.yml
Labels: status: needs review

#4233 Use qt to equally size tabs
  qutebrowser/mainwindow/tabwidget.py
Labels: component: performance, status: needs review

#4234 Only repaint tabs when they are needed
  qutebrowser/mainwindow/tabwidget.py
Labels: component: performance, status: needs review

#4246 Avoid calls to minTabSizeHint in tabSizeHint
  qutebrowser/mainwindow/tabwidget.py
Labels: component: performance, status: needs review

#4186 (QtWebEngine) Unhide scrollbar on search result
  qutebrowser/browser/shared.py
  qutebrowser/browser/webengine/webenginetab.py
  qutebrowser/config/configdata.yml
  qutebrowser/config/configfiles.py
Labels: status: needs review

#4191 Adblock import handles local directories and paths
  qutebrowser/browser/adblock.py
  tests/unit/browser/test_adblock.py
Labels: component: config, easy, priority: 2 - low, status: needs review, status: work in progress

#4274 FAQ: Add MacOS PATH info to Troubleshooting
  doc/faq.asciidoc
Labels: status: needs review
