Repository qutebrowser/qutebrowser, pull requests merged in 2018-11, with the labels that each got.

#4420 Allow password_fill to work without final newline
  misc/userscripts/password_fill
Labels: status: needs review

#4408 Strip fragment and query only for `:navigate up`
  doc/changelog.asciidoc
  qutebrowser/browser/commands.py
  tests/end2end/features/navigate.feature
Labels: bug: behavior, priority: 2 - low, status: needs review

#4412 Don't complete url and title from same search word.
  qutebrowser/completion/models/histcategory.py
  tests/unit/completion/test_histcategory.py
Labels: bug: behavior, component: completion, priority: 2 - low, status: needs review

#4428 Fix FAQ grammar
  doc/faq.asciidoc
Labels: status: needs review

#4431 Change some language about autoconfig to be clearer
  doc/help/configuring.asciidoc
Labels: status: needs review
