Repository qutebrowser/qutebrowser, pull requests merged in 2018-10, with the labels that each got.

#4282 Fix url available to :navigate (strip query)
  qutebrowser/browser/commands.py
Labels: bug: behavior, priority: 2 - low, status: needs review

#4046 make the host_blocker aware of patterns
  qutebrowser/browser/adblock.py
  qutebrowser/browser/webengine/interceptor.py
  qutebrowser/browser/webkit/network/networkmanager.py
  qutebrowser/config/configdata.yml
Labels: status: needs review, status: stale

#4296 Fix tabs appearing when updating all tab titles
  qutebrowser/mainwindow/tabwidget.py
  tests/unit/mainwindow/test_tabwidget.py
Labels: bug: behavior, priority: 0 - high, status: needs review

#4306 Cache config accesses in minimumTabSizeHint
  qutebrowser/mainwindow/tabwidget.py
Labels: component: performance, status: needs review

#4324 New config: More powerful :config- commands: remove
  qutebrowser/config/configcommands.py
  tests/unit/config/test_configcommands.py
Labels: status: needs review

#4342 Optimize HintLabel.update_text
  qutebrowser/browser/hints.py
Labels: component: performance, status: needs review

#4332 Cache hot config accesses in completion
  qutebrowser/completion/completiondelegate.py
Labels: component: performance, status: needs review

#4352 Fix docstring for HintManager.filter_hints
  qutebrowser/browser/hints.py
Labels: status: needs review

#4363 Fix _partial_timer connection in modeparsers
  qutebrowser/keyinput/modeparsers.py
Labels: status: needs review

#4381 Fix dragging with visibility toggle
  qutebrowser/mainwindow/tabwidget.py
Labels: status: needs review

#4361 Cache hot config accesses for hints
  qutebrowser/browser/hints.py
Labels: component: performance, status: needs review

#4362 Simplify logic in HintKeyParser.handle
  qutebrowser/keyinput/modeparsers.py
Labels: status: needs review

#4386 Upgrade itsdangerous to 1.1.0
  misc/requirements/requirements-tests.txt
Labels: priority: 0 - high, status: needs review

#4382 Fix selection clearing when using <shift-home>
  qutebrowser/misc/miscwidgets.py
  tests/unit/misc/test_miscwidgets.py
Labels: bug: behavior, priority: 2 - low, status: needs review
