Repository qutebrowser/qutebrowser, pull requests merged in 2018-07, with the labels that each got.

#4019 Fix crash when tab is closed after a per-domain forced reload
  qutebrowser/browser/webengine/webenginetab.py
Labels: status: needs review

#4089 Move audible strings into class variables
  qutebrowser/mainwindow/tabwidget.py
Labels: status: needs review

#4080 [qute-pass] Follow symlinks when finding pass candidates
  misc/userscripts/qute-pass
Labels: status: needs review

#4090 Add catch and error handling for errors in follow_selected click
  qutebrowser/browser/webengine/webenginetab.py
Labels: bug: exception, priority: 1 - middle, status: needs review

#4072 Process all events before issuing an alert
  qutebrowser/mainwindow/mainwindow.py
Labels: bug: behavior, priority: 2 - low
