Repository qutebrowser/qutebrowser, pull requests merged in 2018-02, with the labels that each got.

#3544 Use the instance attribute instead of querying the registry
  qutebrowser/mainwindow/mainwindow.py
Labels: status: needs review, status: stale

#3554 Add a new --no-last flag to :tab-focus
  doc/help/commands.asciidoc
  qutebrowser/browser/commands.py
Labels: component: ui, status: needs review

#3555 Delete QWebEngineDownloadItem objects when wrapper object is deleted
  qutebrowser/browser/webengine/webenginedownloads.py
Labels: priority: 2 - low, status: needs review, status: needs triage

#3558 Fix going back twice on lazy loading a tab
  qutebrowser/html/back.html
Labels: bug: behavior, priority: 1 - middle, status: needs review

#3565 Add troubleshooting info for widevine to FAQ
  doc/faq.asciidoc
Labels: status: needs review

#3581 [count] overrides win_id for tab-give cmd
  qutebrowser/browser/commands.py
Labels: priority: 2 - low, status: needs review

#3587 Update tab scroll position when finished loading.
  qutebrowser/browser/webengine/webenginetab.py
Labels: bug: behavior, component: QtWebEngine

#3602 Fix broken language links in contributing
  doc/contributing.asciidoc
Labels: component: docs, priority: 3 - wishlist, status: needs review

#3607 Add scoop installer
  doc/install.asciidoc
Labels: status: needs review

#3592 Fix caret being cleared when leaving any mode
  qutebrowser/browser/browsertab.py
  qutebrowser/browser/webengine/webenginetab.py
  qutebrowser/browser/webkit/webkittab.py
Labels: component: QtWebEngine, priority: 1 - middle, status: stale

#3603 Add tor_identity userscript.
  misc/userscripts/tor_identity
Labels: status: needs review

#3610 Use QUTE_DATA_DIR in readability userscript
  misc/userscripts/readability
Labels: status: needs review

#3617 use up to date cheatsheet images from repo instead of qutebrowser.org
  README.asciidoc
  scripts/asciidoc2html.py
Labels: status: needs review

#3637 Handle invalid URLs on Apple events
  qutebrowser/app.py
Labels: status: needs review

#3620 Convert searched text to a selection when enetering caret mode
  pytest.ini
  qutebrowser/browser/webengine/webenginetab.py
  tests/conftest.py
  tests/end2end/features/caret.feature
Labels: component: QtWebEngine, priority: 3 - wishlist, status: needs review
