Repository qutebrowser/qutebrowser, pull requests merged in 2019-02, with the labels that each got.

#4463 Remove outdated X-Do-Not-Track
  doc/changelog.asciidoc
  qutebrowser/browser/shared.py
  tests/end2end/features/misc.feature
  tests/unit/browser/test_shared.py
Labels: easy, priority: 2 - low, status: needs review

#4424 stylesheet.js: Check if document.documentElement exists
  doc/changelog.asciidoc
  qutebrowser/javascript/stylesheet.js
Labels: bug: behavior, priority: 0 - high, qt: 5.12, status: needs review

#4528 doc: link CVE [ci skip]
  doc/changelog.asciidoc
Labels: status: needs review

#4567 Add setting for DnsPrefetchEnabled
  qutebrowser/browser/webengine/webenginesettings.py
  qutebrowser/config/configdata.py
  qutebrowser/config/configdata.yml
Labels: status: needs review

#4604 GreaseMonkey: Force document-end for known-broken scripts
  qutebrowser/browser/greasemonkey.py
  qutebrowser/browser/webengine/webenginetab.py
  tests/unit/browser/webengine/test_webenginetab.py
  tests/unit/javascript/test_greasemonkey.py
Labels: status: needs review
