Repository qutebrowser/qutebrowser, pull requests merged in 2019-04, with the labels that each got.

#4689 Fix some 5.13 test failures
  tests/end2end/features/downloads.feature
  tests/end2end/features/history.feature
  tests/unit/browser/test_caret.py
Labels: status: needs review

#4698 Fix missing reference to SqlError
  qutebrowser/misc/sql.py
Labels: priority: 0 - high

#4716 make qute-pass more informative when no matching pass entry is found
  misc/userscripts/qute-pass
Labels: jay: gold

#4652 Add more variables (cont.)
  qutebrowser/commands/runners.py
  tests/end2end/features/misc.feature
  tests/end2end/misc/test_runners_e2e.py
Labels: jay: silver, status: needs review

#4555 Add basic_str_validation cache
  qutebrowser/config/configtypes.py
  qutebrowser/misc/utilcmds.py
  tests/unit/config/test_config.py
Labels: component: performance, jay: gold, status: needs review
