Repository qutebrowser/qutebrowser, pull requests merged in 2019-01, with the labels that each got.

#4518 Optimize configcache for critical path
  qutebrowser/config/configcache.py
  tests/unit/config/test_configcache.py
Labels: component: performance, status: needs review

#4524 Fix match highlighting on qt 5.11.3 and 5.12.1+
  qutebrowser/completion/completiondelegate.py
Labels: bug: behavior, component: completion, priority: 1 - middle, qt, status: needs review

#4526 Update qutebrowser.org/doc/faq.html question
  doc/faq.asciidoc
Labels: status: needs review

#4388 Add support for per-domain secret files in qute-pass
  doc/changelog.asciidoc
  misc/userscripts/qute-pass
Labels: status: needs review
