Repository qutebrowser/qutebrowser, pull requests merged in 2019-03, with the labels that each got.

#4309 Always show icons for pinned tabs
  qutebrowser/mainwindow/tabwidget.py
  tests/unit/mainwindow/test_tabwidget.py
Labels: status: needs review, status: work in progress

#4629 Fix config path for Windows in doc
  doc/help/configuring.asciidoc
Labels: status: needs review

#4644 Fix broken link in contributing.asciidoc
  doc/contributing.asciidoc
Labels: status: needs review

#4624 Add undefined actions to action list
  misc/org.qutebrowser.qutebrowser.desktop
Labels: status: needs review

#4570 Resize SVG to comply with freedesktop standard
  icons/qutebrowser.svg
Labels: status: needs review

#4627 Only set background color on StatusBar
  qutebrowser/mainwindow/statusbar/bar.py
Labels: status: needs review

#4635 Delete disconnected IPC sockets.
  qutebrowser/misc/ipc.py
Labels: status: needs review

#4654 Create color attributes for pinned tabs
  qutebrowser/config/configdata.yml
  qutebrowser/mainwindow/tabwidget.py
Labels: status: needs review

#4676 Fix a few lgtm warnings
  misc/userscripts/qute-keepass
  qutebrowser/completion/completionwidget.py
  qutebrowser/mainwindow/mainwindow.py
  qutebrowser/mainwindow/tabwidget.py
Labels: status: needs review

#4683 Use OR instead of concatenation for queries
  qutebrowser/completion/models/histcategory.py
Labels: component: completion, component: performance

#4515 Default to white background
  www/qute.css
Labels: bug: behavior, component: website, jay: platinum, priority: 2 - low, status: needs review

#4620 Ignore caret callbacks when outside of caret mode
  qutebrowser/browser/browsertab.py
  qutebrowser/browser/webengine/webenginetab.py
Labels: jay: gold, status: needs review

#4637 Apply hint stylesheet on main application
  qutebrowser/browser/hints.py
  qutebrowser/mainwindow/mainwindow.py
Labels: component: performance, jay: gold, status: needs review
