Repository qutebrowser/qutebrowser, pull requests merged in 2020-08, with the labels that each got.

#4438 Add :navigate strip
  doc/changelog.asciidoc
  doc/help/commands.asciidoc
  doc/help/settings.asciidoc
  qutebrowser/browser/commands.py
  qutebrowser/config/configdata.yml
  tests/end2end/features/navigate.feature
Labels: jay: silver

#4391 Touch the file to be downloaded so it's not silently overwritten
  qutebrowser/browser/downloads.py
  qutebrowser/browser/qtnetworkdownloads.py
  qutebrowser/browser/webengine/webenginedownloads.py
  tests/unit/browser/webkit/test_downloads.py
Labels: bug: behavior, component: downloads, priority: 0 - high

#4490 Wrap messges when the text is too long
  qutebrowser/mainwindow/mainwindow.py
  qutebrowser/mainwindow/messageview.py
Labels: component: ui, jay: gold, priority: 2 - low

#4147 Clear private data when closing last private window
  qutebrowser/browser/webengine/webenginesettings.py
  qutebrowser/config/websettings.py
  qutebrowser/mainwindow/mainwindow.py
  tests/end2end/features/private.feature
Labels: bug: behavior, jay: silver, priority: 0 - high
