Repository qutebrowser/qutebrowser, pull requests merged in 2020-07, with the labels that each got.

#4807 Add :undo --window
  doc/help/commands.asciidoc
  doc/help/settings.asciidoc
  qutebrowser/app.py
  qutebrowser/browser/commands.py
  qutebrowser/completion/models/miscmodels.py
  qutebrowser/config/configdata.yml
  qutebrowser/mainwindow/mainwindow.py
  qutebrowser/mainwindow/tabbedbrowser.py
  tests/end2end/features/conftest.py
  tests/end2end/features/tabs.feature
  tests/helpers/stubs.py
Labels: jay: silver

#4645 Add a 'private-window' --target
  qutebrowser/app.py
  qutebrowser/config/configdata.yml
  qutebrowser/mainwindow/mainwindow.py
  qutebrowser/qutebrowser.py
  tests/end2end/features/invoke.feature
Labels: easy, jay: silver, priority: 3 - wishlist

#4180 Add completion for :back/:forward
  doc/help/commands.asciidoc
  qutebrowser/browser/browsertab.py
  qutebrowser/browser/commands.py
  qutebrowser/browser/webengine/tabhistory.py
  qutebrowser/browser/webengine/webenginetab.py
  qutebrowser/browser/webkit/webkittab.py
  qutebrowser/completion/models/completionmodel.py
  qutebrowser/completion/models/miscmodels.py
  qutebrowser/misc/sessions.py
  tests/unit/completion/test_models.py
Labels: component: completion, jay: silver
